name: Code style

on: [push, pull_request]

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}
    runs-on: ${{ matrix.operating-system }}
    name: PHP/PHTML/CSS

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['7.1', '7.2', '7.3', '7.4']
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: 'development'

      - uses: actions/checkout@v4

      - run: composer validate

      - run: composer install --no-progress

      - run: composer webtrees:phpcs
